name: app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.5
  provider: ^6.0.0
  loading_indicator: ^3.1.0
  flutter_swiper_plus: ^2.0.4
  marquee: ^2.2.3
  font_awesome_flutter: ^10.1.0
  vibration: ^1.7.6
  intl: ^0.17.0
  flash: ^2.0.3+3
  collection: ^1.16.0
  url_launcher: ^6.1.5
  photo_view: ^0.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name:
  flutter_launcher_icons:

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/audios/

  fonts:
    - family: Courier
      fonts:
        - asset: assets/fonts/courier-regular.ttf
        - asset: assets/fonts/courier-bold.ttf
        - weight: 700
    - family: Fira
      fonts:
        - asset: assets/fonts/fira-regular.ttf
        - asset: assets/fonts/fira-bold.ttf
          weight: 700
    - family: Myanmar
      fonts:
        - asset: assets/fonts/Pyidaungsu-Regular.ttf
        - asset: assets/fonts/Pyidaungsu-Bold.ttf
          weight: 700
